# Site settings
title: Siva's blog
email: 
description: "My Learnings"
baseurl: "/blog"
url: 
twitter_username: meredilettante
github_username:  quantum-sage

avatar: '/home/sivarama-12850/blog/assets/minions1.png'

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge