# Site settings
title: Siva's blog
email: 
description: "My Learnings"
baseurl: "/blog"
url: 
twitter_username: meredilettante
github_username:  quantum-sage

avatar: https://raw.githubusercontent.com/quantum-sage/blog/master/assets/minions1.png

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge