# Site settings
title: Siva's blog
email: 
description: "My Experiments"
url: "https://quantum-sage.github.io"
baseurl: "/blog"
twitter_username: meredilettante
github_username:  quantum-sage

avatar: 'assets/minions1.png'
future: true

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge