# Site settings
title: Byte Logs
email: 
description: "Rants from a galaxy far far away"
url: ""
baseurl: ""
twitter_username: mark_madhukar_
github_username:  programmer2215

avatar: 'assets/retro-comp.png'
future: true

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge